version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle123
    restart: unless-stopped
